Repository YAPP-Github/25th-Web-Team-3-BE, pull requests merged in 2025-01, with the labels that each got.

#9 [FEAT] Kotlin JDSL을 적용한 무한 스크롤 카페 목록 조회 기능 구현
  build.gradle.kts
  src/main/kotlin/com/coffee/api/cafe/application/CafeService.kt
  src/main/kotlin/com/coffee/api/cafe/application/repository/CafeRepository.kt
  src/main/kotlin/com/coffee/api/cafe/application/usecase/FindCafe.kt
  src/main/kotlin/com/coffee/api/cafe/domain/Cafe.kt
  src/main/kotlin/com/coffee/api/cafe/domain/CafePage.kt
  src/main/kotlin/com/coffee/api/cafe/domain/Flavor.kt
  src/main/kotlin/com/coffee/api/cafe/domain/RoastingPoint.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/CafeConverter.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/entity/CafeEntity.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/entity/CafeTagEntity.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/entity/CoffeeBeanEntity.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/entity/MenuEntity.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/entity/TagEntity.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/repository/CafeJpaRepositoryImpl.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/repository/CafeRepositoryImpl.kt
  src/main/kotlin/com/coffee/api/cafe/presentation/CafeController.kt
  src/main/kotlin/com/coffee/api/cafe/presentation/docs/CafeApi.kt
  src/main/kotlin/com/coffee/api/config/JdslConfiguration.kt
  src/main/resources/application.yml
Labels: :sparkles: feature, :recycle: refactor

#12 [FEAT] CI-CD 워크플로우 작성
  .editorconfig
  .github/workflows/ci-cd-api-server.yaml
  .github/workflows/lint.yaml
  .gitignore
  Dockerfile
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/gradle/wrapper/gradle-wrapper.jar
  buildSrc/gradle/wrapper/gradle-wrapper.properties
  buildSrc/gradlew
  buildSrc/gradlew.bat
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Plugin.kt
  src/main/kotlin/com/coffee/api/ApiApplication.kt
  src/main/kotlin/com/coffee/api/cafe/application/CafeService.kt
  src/main/kotlin/com/coffee/api/cafe/application/repository/CafeRepository.kt
  src/main/kotlin/com/coffee/api/cafe/application/usecase/FindCafe.kt
  src/main/kotlin/com/coffee/api/cafe/domain/Cafe.kt
  src/main/kotlin/com/coffee/api/cafe/domain/CafePage.kt
  src/main/kotlin/com/coffee/api/cafe/domain/Flavor.kt
  src/main/kotlin/com/coffee/api/cafe/domain/RoastingPoint.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/CafeConverter.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/entity/CafeEntity.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/entity/CafeTagEntity.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/entity/CoffeeBeanEntity.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/entity/MenuEntity.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/entity/TagEntity.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/repository/CafeJpaRepository.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/repository/CafeRepositoryImpl.kt
  src/main/kotlin/com/coffee/api/cafe/presentation/CafeController.kt
  src/main/kotlin/com/coffee/api/cafe/presentation/docs/CafeApi.kt
  src/main/kotlin/com/coffee/api/common/presentation/response/ApiResponseGenerator.kt
  src/main/kotlin/com/coffee/api/config/JdslConfiguration.kt
  src/main/kotlin/com/coffee/api/config/SwaggerConfig.kt
  src/main/kotlin/com/coffee/api/config/WebMvcConfig.kt
  src/main/kotlin/com/coffee/api/foo/application/usecase/CreateFoo.kt
  src/main/kotlin/com/coffee/api/foo/domain/Foo.kt
  src/main/kotlin/com/coffee/api/foo/infrastructure/persistence/entity/FooEntity.kt
  src/main/kotlin/com/coffee/api/foo/presentation/FooController.kt
  src/main/kotlin/com/coffee/api/foo/presentation/response/SaveFooResponse.kt
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/kotlin/com/coffee/api/ApiApplicationTests.kt
Labels: :gear: infra

#16 [FEAT] 카페 상세 조회 기능 구현
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependency.kt
  coderabbit.yaml
  src/main/kotlin/com/coffee/api/cafe/application/CafeDetailsService.kt
  src/main/kotlin/com/coffee/api/cafe/application/repository/CafeRepository.kt
  src/main/kotlin/com/coffee/api/cafe/application/usecase/FindCafe.kt
  src/main/kotlin/com/coffee/api/cafe/application/usecase/FindCafeDetails.kt
  src/main/kotlin/com/coffee/api/cafe/domain/CafeDetails.kt
  src/main/kotlin/com/coffee/api/cafe/domain/CoffeeBean.kt
  src/main/kotlin/com/coffee/api/cafe/domain/Menu.kt
  src/main/kotlin/com/coffee/api/cafe/domain/Tag.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/CoffeeBeanConverter.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/MenuConverter.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/TagConverter.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/entity/CafeTagEntity.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/entity/CoffeeBeanEntity.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/entity/MenuEntity.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/entity/TagEntity.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/repository/CafeRepositoryImpl.kt
  src/main/kotlin/com/coffee/api/cafe/presentation/CafeController.kt
  src/main/kotlin/com/coffee/api/cafe/presentation/docs/CafeApi.kt
  src/main/kotlin/com/coffee/api/config/JdslConfiguration.kt
  src/main/kotlin/com/coffee/api/config/SwaggerConfig.kt
  src/main/resources/application.yml
Labels: :sparkles: feature

#21 [FEAT] 카페 리스트 조회 시 태그 함께 반환하도록 수정
  src/main/kotlin/com/coffee/api/cafe/application/CafeService.kt
  src/main/kotlin/com/coffee/api/cafe/application/usecase/FindCafe.kt
  src/main/kotlin/com/coffee/api/cafe/domain/CafeInfoWithTags.kt
  src/main/kotlin/com/coffee/api/cafe/domain/CafePage.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/repository/CafeRepositoryImpl.kt
Labels: :sparkles: feature

#24 [SETTING] api response exception
  src/main/kotlin/com/coffee/api/cafe/presentation/CafeController.kt
  src/main/kotlin/com/coffee/api/cafe/presentation/docs/CafeApi.kt
  src/main/kotlin/com/coffee/api/common/presentation/response/ApiResponse.kt
  src/main/kotlin/com/coffee/api/common/presentation/response/ApiResponseGenerator.kt
  src/main/kotlin/com/coffee/api/common/support/error/CoreApiException.kt
  src/main/kotlin/com/coffee/api/common/support/error/ErrorCode.kt
  src/main/kotlin/com/coffee/api/common/support/error/ErrorMessage.kt
  src/main/kotlin/com/coffee/api/common/support/error/ErrorType.kt
  src/main/kotlin/com/coffee/api/common/support/response/ApiResponse.kt
  src/main/kotlin/com/coffee/api/common/support/response/ResultType.kt
  src/main/kotlin/com/coffee/api/config/ApiControllerAdvice.kt
  src/main/kotlin/com/coffee/api/foo/application/FooService.kt
  src/main/kotlin/com/coffee/api/foo/application/repository/FooRepository.kt
  src/main/kotlin/com/coffee/api/foo/application/usecase/CreateFoo.kt
  src/main/kotlin/com/coffee/api/foo/domain/Foo.kt
  src/main/kotlin/com/coffee/api/foo/infrastructure/persistence/FooConverter.kt
  src/main/kotlin/com/coffee/api/foo/infrastructure/persistence/entity/FooEntity.kt
  src/main/kotlin/com/coffee/api/foo/infrastructure/persistence/repository/FooJpaRepository.kt
  src/main/kotlin/com/coffee/api/foo/infrastructure/persistence/repository/FooRepositoryImpl.kt
  src/main/kotlin/com/coffee/api/foo/presentation/FooController.kt
  src/main/kotlin/com/coffee/api/foo/presentation/request/SaveFooRequest.kt
  src/main/kotlin/com/coffee/api/foo/presentation/response/SaveFooResponse.kt
Labels: :sparkles: feature

#27 [FEAT] 프론트 요구사항 반영 및 헥사고날 아키텍처 전환
  src/main/kotlin/com/coffee/api/cafe/application/CafeDetailsService.kt
  src/main/kotlin/com/coffee/api/cafe/application/CafeService.kt
  src/main/kotlin/com/coffee/api/cafe/application/model/CafeDetails.kt
  src/main/kotlin/com/coffee/api/cafe/application/model/CafeInfoWithTags.kt
  src/main/kotlin/com/coffee/api/cafe/application/model/CafePage.kt
  src/main/kotlin/com/coffee/api/cafe/application/port/inbound/FindCafe.kt
  src/main/kotlin/com/coffee/api/cafe/application/port/inbound/FindCafeDetails.kt
  src/main/kotlin/com/coffee/api/cafe/application/port/outbound/CafeRepository.kt
  src/main/kotlin/com/coffee/api/cafe/application/usecase/FindCafe.kt
  src/main/kotlin/com/coffee/api/cafe/application/usecase/FindCafeDetails.kt
  src/main/kotlin/com/coffee/api/cafe/domain/Cafe.kt
  src/main/kotlin/com/coffee/api/cafe/domain/CoffeeBean.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/CafeConverter.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/CoffeeBeanConverter.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/entity/CafeEntity.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/entity/CoffeeBeanEntity.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/repository/CafeRepositoryImpl.kt
  src/main/kotlin/com/coffee/api/cafe/presentation/CafeController.kt
  src/main/kotlin/com/coffee/api/cafe/presentation/adapter/controller/CafeController.kt
  src/main/kotlin/com/coffee/api/cafe/presentation/adapter/dto/response/CafeResponse.kt
  src/main/kotlin/com/coffee/api/cafe/presentation/adapter/dto/response/CoffeeBeanResponse.kt
  src/main/kotlin/com/coffee/api/cafe/presentation/adapter/dto/response/FindAllCafesResponse.kt
  src/main/kotlin/com/coffee/api/cafe/presentation/adapter/dto/response/GetCafeDetailsResponse.kt
  src/main/kotlin/com/coffee/api/cafe/presentation/adapter/dto/response/MenuResponse.kt
  src/main/kotlin/com/coffee/api/cafe/presentation/adapter/dto/response/TagResponse.kt
  src/main/kotlin/com/coffee/api/cafe/presentation/docs/CafeApi.kt
  src/main/kotlin/com/coffee/api/config/ApiControllerAdvice.kt
Labels: :sparkles: feature, :recycle: refactor

#29 [FIX] ASG 버전 에러 수정
  src/main/kotlin/com/coffee/api/cafe/domain/Cafe.kt
  src/main/kotlin/com/coffee/api/helper/uuid/UUIDProvider.kt
Labels: :bug: bug, :gear: infra

#38 [FEATURE] 카페 추천 그룹 조회 API
  src/main/kotlin/com/coffee/api/cafe/application/CafeRecommendGroupService.kt
  src/main/kotlin/com/coffee/api/cafe/application/port/inbound/FindRecommendCafe.kt
  src/main/kotlin/com/coffee/api/cafe/application/port/outbound/CafeRepository.kt
  src/main/kotlin/com/coffee/api/cafe/application/port/outbound/model/CafeInfoWithRecommendGroups.kt
  src/main/kotlin/com/coffee/api/cafe/domain/CafeRecommendGroup.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/CafeRecommendGroupConverter.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/entity/CafeRecommendGroupEntity.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/entity/CafeRecommendGroupMappingEntity.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/repository/CafeRepositoryImpl.kt
  src/main/kotlin/com/coffee/api/cafe/presentation/adapter/controller/CafeController.kt
  src/main/kotlin/com/coffee/api/cafe/presentation/docs/CafeApi.kt
  src/main/kotlin/com/coffee/api/common/domain/SliceDomain.kt
  src/main/kotlin/com/coffee/api/common/presentation/constant/SliceConstants.kt
Labels: :sparkles: feature

#39 [FEAT] 카페 필터링
  src/main/kotlin/com/coffee/api/cafe/application/CafeAreaService.kt
  src/main/kotlin/com/coffee/api/cafe/application/CafeService.kt
  src/main/kotlin/com/coffee/api/cafe/application/port/inbound/FindCafe.kt
  src/main/kotlin/com/coffee/api/cafe/application/port/inbound/FindCafeArea.kt
  src/main/kotlin/com/coffee/api/cafe/application/port/outbound/CafeRepository.kt
  src/main/kotlin/com/coffee/api/cafe/domain/Cafe.kt
  src/main/kotlin/com/coffee/api/cafe/domain/CafeArea.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/CafeConverter.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/entity/CafeEntity.kt
  src/main/kotlin/com/coffee/api/cafe/infrastructure/persistence/repository/CafeRepositoryImpl.kt
  src/main/kotlin/com/coffee/api/cafe/presentation/adapter/controller/CafeController.kt
  src/main/kotlin/com/coffee/api/cafe/presentation/docs/CafeApi.kt
Labels: :sparkles: feature
